<?php

namespace Database\Seeders;

use App\Enums\AlatKondisi;
use App\Enums\AlatReviewStatus;
use App\Enums\AlatStatusKepemilikan;
use App\Enums\KalibrasiHasil;
use App\Models\Alat;
use App\Models\AlatKalibrasi;
use App\Models\Cabang;
use App\Models\User;
use Illuminate\Database\Seeder;

class AlatSeeder extends Seeder
{
    public function run(): void
    {
        $priok = Cabang::where('code', 'TGP')->first();
        $surabaya = Cabang::where('code', 'SBY')->first();
        $makassar = Cabang::where('code', 'MKS')->first();
        $belawan = Cabang::where('code', 'BLW')->first();
        $banjarmasin = Cabang::where('code', 'BJM')->first();
        $palembang = Cabang::where('code', 'PLB')->first();
        $batam = Cabang::where('code', 'BTM')->first();
        $cirebon = Cabang::where('code', 'CRB')->first();
        $bitung = Cabang::where('code', 'BTG')->first();
        $sorong = Cabang::where('code', 'SRG')->first();
        $ambon = Cabang::where('code', 'AMB')->first();
        $samarinda = Cabang::where('code', 'SMD')->first();
        $singapore = Cabang::where('code', 'SGP')->first();
        $jambi = Cabang::where('code', 'JBI')->first();
        $pontianak = Cabang::where('code', 'PNK')->first();
        $pekanbaru = Cabang::where('code', 'PKB')->first();
        $semarang = Cabang::where('code', 'SMG')->first();
        $banten = Cabang::where('code', 'BTN')->first();
        $admin = User::where('email', 'admin@app.com')->first();

        if (! $priok || ! $surabaya || ! $makassar || ! $belawan) {
            return;
        }

        $alats = [
            [
                'code' => 'ALT-001',
                'name' => 'Multimeter Digital Fluke 87V',
                'merk_type' => 'Fluke 87V',
                'serial_number' => 'FLK87V-23984756',
                'kode_inventaris' => 'INV-ALT-001',
                'description' => 'Multimeter digital True-RMS untuk pengukuran tegangan, arus, resistansi.',
                'cabang_id' => $priok->id,
                'lokasi' => 'Ruang Lab Kalibrasi 1',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(30),
                'approval_note' => 'Alat layak digunakan.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2024-01-15',
                        'tanggal_kalibrasi_berikutnya' => '2025-01-15',
                        'vendor' => 'Kalibrasi Teknik Nusantara',
                        'sertifikat_no' => 'KAL-2024-001',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Hasil kalibrasi baik, alat layak pakai.',
                    ],
                    [
                        'tanggal_kalibrasi' => '2026-01-15',
                        'tanggal_kalibrasi_berikutnya' => '2027-01-15',
                        'vendor' => 'Kalibrasi Teknik Nusantara',
                        'sertifikat_no' => 'KAL-2026-001',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi tahunan, semua parameter dalam toleransi.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-002',
                'name' => 'Caliper Digital Mitutoyo 500-196-30',
                'merk_type' => 'Mitutoyo 500-196-30',
                'serial_number' => 'MTY-500196-98765432',
                'kode_inventaris' => 'INV-ALT-002',
                'description' => 'Jangka sorong digital 0-150mm dengan akurasi 0.01mm.',
                'cabang_id' => $priok->id,
                'lokasi' => 'Ruang Lab Kalibrasi 1',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(60),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2024-01-10',
                        'tanggal_kalibrasi_berikutnya' => '2025-01-10',
                        'vendor' => 'PT Metrologi Indonesia',
                        'sertifikat_no' => 'KAL-2024-002',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Akurasi terpenuhi.',
                    ],
                    [
                        'tanggal_kalibrasi' => '2025-01-10',
                        'tanggal_kalibrasi_berikutnya' => '2026-01-10',
                        'vendor' => 'PT Metrologi Indonesia',
                        'sertifikat_no' => 'KAL-2025-002',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi ulang tahunan.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-003',
                'name' => 'Torque Wrench Snap-on QD3R250A',
                'merk_type' => 'Snap-on QD3R250A',
                'serial_number' => 'SNO-QD3R-11223344',
                'kode_inventaris' => 'INV-ALT-003',
                'description' => 'Kunci momen 30-250 Nm dengan akurasi ±4%.',
                'cabang_id' => $surabaya->id,
                'lokasi' => 'Workshop 2',
                'kondisi' => AlatKondisi::RusakRingan->value,
                'status_kepemilikan' => AlatStatusKepemilikan::Sewa->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Pending->value,
                'kalibrasis' => [],
            ],
            [
                'code' => 'ALT-004',
                'name' => 'Thermohygrometer Testo 608-H1',
                'merk_type' => 'Testo 608-H1',
                'serial_number' => 'TST-608H1-44556677',
                'kode_inventaris' => 'INV-ALT-004',
                'description' => 'Pengukur suhu & kelembaban ruangan.',
                'cabang_id' => $makassar->id,
                'lokasi' => 'Lab Pengujian 3',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(15),
                'approval_note' => 'OK.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-02-01',
                        'tanggal_kalibrasi_berikutnya' => now()->addDays(20)->format('Y-m-d'),
                        'vendor' => 'Testo Service Center',
                        'sertifikat_no' => 'KAL-2026-004',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Jatuh tempo dalam 20 hari.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-005',
                'name' => 'Oscilloscope Rigol DS1054Z',
                'merk_type' => 'Rigol DS1054Z',
                'serial_number' => 'RGL-DS1054-88990011',
                'kode_inventaris' => 'INV-ALT-005',
                'description' => 'Oscilloscope digital 4 channel 50 MHz.',
                'cabang_id' => $belawan->id,
                'lokasi' => 'Lab Elektronik',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::Leasing->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(10),
                'approval_note' => 'Approved.',
                'kalibrasis' => [],
            ],
            [
                'code' => 'ALT-006',
                'name' => 'Pressure Gauge WIKA 232.50',
                'merk_type' => 'WIKA 232.50',
                'serial_number' => 'WKA-23250-22334455',
                'kode_inventaris' => 'INV-ALT-006',
                'description' => 'Manometer 0-10 bar dengan diameter 100mm.',
                'cabang_id' => $priok->id,
                'lokasi' => 'Ruang Kalibrasi 2',
                'kondisi' => AlatKondisi::RusakBerat->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => false,
                'review_status' => AlatReviewStatus::Rejected->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(5),
                'rejection_reason' => 'Alat rusak berat, perlu penggantian.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2023-06-01',
                        'tanggal_kalibrasi_berikutnya' => '2024-06-01',
                        'vendor' => 'WIKA Service',
                        'sertifikat_no' => 'KAL-2023-006',
                        'hasil' => KalibrasiHasil::PerluPerbaikan->value,
                        'catatan' => 'Perlu kalibrasi ulang setelah perbaikan.',
                    ],
                    [
                        'tanggal_kalibrasi' => '2024-06-01',
                        'tanggal_kalibrasi_berikutnya' => '2025-06-01',
                        'vendor' => 'WIKA Service',
                        'sertifikat_no' => 'KAL-2024-006',
                        'hasil' => KalibrasiHasil::Gagal->value,
                        'catatan' => 'Alat tidak lulus kalibrasi, rusak berat.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-007',
                'name' => 'Clamp Meter Fluke 376 FC',
                'merk_type' => 'Fluke 376 FC',
                'serial_number' => 'FLK-376FC-66778899',
                'kode_inventaris' => 'INV-ALT-007',
                'description' => 'Clamp meter True-RMS AC/DC dengan Bluetooth untuk logging.',
                'cabang_id' => $belawan->id,
                'lokasi' => 'Lab Listrik Belawan',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(8),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-01-20',
                        'tanggal_kalibrasi_berikutnya' => '2027-01-20',
                        'vendor' => 'Fluke Calibration Center',
                        'sertifikat_no' => 'KAL-2026-007',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi tahunan, semua parameter OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-008',
                'name' => 'Insulation Tester Kyoritsu 3125A',
                'merk_type' => 'Kyoritsu 3125A',
                'serial_number' => 'KYO-3125A-99887766',
                'kode_inventaris' => 'INV-ALT-008',
                'description' => 'Tester isolasi 5000V untuk pengujian tahanan isolasi kabel.',
                'cabang_id' => $surabaya->id,
                'lokasi' => 'Gudang Alat Surabaya',
                'kondisi' => AlatKondisi::Hilang->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => false,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(45),
                'approval_note' => 'Approved sebelum dilaporkan hilang.',
                'kalibrasis' => [],
            ],
            // 14 alat untuk cabang yang belum punya alat (1 per cabang)
            [
                'code' => 'ALT-009',
                'name' => 'Sound Level Meter Cesva SC-160',
                'merk_type' => 'Cesva SC-160',
                'serial_number' => 'CSV-SC160-11000111',
                'kode_inventaris' => 'INV-ALT-009',
                'description' => 'Pengukur tingkat kebisingan kelas 2.',
                'cabang_id' => $banjarmasin->id,
                'lokasi' => 'Lab Pengujian Banjarmasin',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(20),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-01-05',
                        'tanggal_kalibrasi_berikutnya' => '2027-01-05',
                        'vendor' => 'Cesva Calibration',
                        'sertifikat_no' => 'KAL-2026-009',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi tahunan OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-010',
                'name' => 'Lux Meter Konica Minolta T-10A',
                'merk_type' => 'Konica Minolta T-10A',
                'serial_number' => 'KMK-T10A-22000222',
                'kode_inventaris' => 'INV-ALT-010',
                'description' => 'Pengukur pencahayaan digital.',
                'cabang_id' => $palembang->id,
                'lokasi' => 'Ruang Kalibrasi Palembang',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(12),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2025-06-01',
                        'tanggal_kalibrasi_berikutnya' => now()->addDays(15)->format('Y-m-d'),
                        'vendor' => 'Minolta Service',
                        'sertifikat_no' => 'KAL-2025-010',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Jatuh tempo dalam 15 hari.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-011',
                'name' => 'Tachometer Digital Extech 461892',
                'merk_type' => 'Extech 461892',
                'serial_number' => 'EXT-461892-33000333',
                'kode_inventaris' => 'INV-ALT-011',
                'description' => 'Pengukur kecepatan putar kontak/non-kontak.',
                'cabang_id' => $batam->id,
                'lokasi' => 'Workshop Batam',
                'kondisi' => AlatKondisi::RusakRingan->value,
                'status_kepemilikan' => AlatStatusKepemilikan::Sewa->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Pending->value,
                'kalibrasis' => [],
            ],
            [
                'code' => 'ALT-012',
                'name' => 'Manometer Bourdon WIKA 611.10',
                'merk_type' => 'WIKA 611.10',
                'serial_number' => 'WKA-61110-44000444',
                'kode_inventaris' => 'INV-ALT-012',
                'description' => 'Manometer 0-25 bar untuk uji tekan.',
                'cabang_id' => $cirebon->id,
                'lokasi' => 'Lab Uji Tekan Cirebon',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(7),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2023-03-01',
                        'tanggal_kalibrasi_berikutnya' => '2024-03-01',
                        'vendor' => 'WIKA Service',
                        'sertifikat_no' => 'KAL-2023-012',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi awal.',
                    ],
                    [
                        'tanggal_kalibrasi' => '2024-03-01',
                        'tanggal_kalibrasi_berikutnya' => '2025-03-01',
                        'vendor' => 'WIKA Service',
                        'sertifikat_no' => 'KAL-2024-012',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Kalibrasi ulang.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-013',
                'name' => 'Anemometer Hot Wire Testo 405i',
                'merk_type' => 'Testo 405i',
                'serial_number' => 'TST-405i-55000555',
                'kode_inventaris' => 'INV-ALT-013',
                'description' => 'Pengukur kecepatan aliran udara.',
                'cabang_id' => $bitung->id,
                'lokasi' => 'Lab HVAC Bitung',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(25),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-02-10',
                        'tanggal_kalibrasi_berikutnya' => '2027-02-10',
                        'vendor' => 'Testo Service Center',
                        'sertifikat_no' => 'KAL-2026-013',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-014',
                'name' => 'Hardness Tester Portable Ernst TWIN',
                'merk_type' => 'Ernst TWIN',
                'serial_number' => 'ERN-TWIN-66000666',
                'kode_inventaris' => 'INV-ALT-014',
                'description' => 'Penguji kekerasan logam portable.',
                'cabang_id' => $sorong->id,
                'lokasi' => 'Workshop Sorong',
                'kondisi' => AlatKondisi::RusakBerat->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => false,
                'review_status' => AlatReviewStatus::Rejected->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(3),
                'rejection_reason' => 'Alat rusak berat, tidak ekonomis diperbaiki.',
                'kalibrasis' => [],
            ],
            [
                'code' => 'ALT-015',
                'name' => 'Borescope Olympus IPLEX GT',
                'merk_type' => 'Olympus IPLEX GT',
                'serial_number' => 'OLY-IPLEX-77000777',
                'kode_inventaris' => 'INV-ALT-015',
                'description' => 'Inspeksi visual endoskopi untuk ruang sempit.',
                'cabang_id' => $ambon->id,
                'lokasi' => 'Lab Inspeksi Ambon',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::Leasing->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(18),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2025-09-01',
                        'tanggal_kalibrasi_berikutnya' => now()->subDays(10)->format('Y-m-d'),
                        'vendor' => 'Olympus Service',
                        'sertifikat_no' => 'KAL-2025-015',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Sudah expired.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-016',
                'name' => 'UT Flaw Detector Olympus EPOCH 650',
                'merk_type' => 'Olympus EPOCH 650',
                'serial_number' => 'OLY-EPOCH-88000888',
                'kode_inventaris' => 'INV-ALT-016',
                'description' => 'Deteksi cacat ultrasonik.',
                'cabang_id' => $samarinda->id,
                'lokasi' => 'Lab NDT Samarinda',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(5),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-03-01',
                        'tanggal_kalibrasi_berikutnya' => '2027-03-01',
                        'vendor' => 'Olympus Calibration',
                        'sertifikat_no' => 'KAL-2026-016',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-017',
                'name' => 'Coating Thickness Gauge Elcometer 456',
                'merk_type' => 'Elcometer 456',
                'serial_number' => 'ELC-456-99000999',
                'kode_inventaris' => 'INV-ALT-017',
                'description' => 'Pengukur ketebalan coating non-destruktif.',
                'cabang_id' => $singapore->id,
                'lokasi' => 'Lab Coating Singapore',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(2),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-01-15',
                        'tanggal_kalibrasi_berikutnya' => '2027-01-15',
                        'vendor' => 'Elcometer Service',
                        'sertifikat_no' => 'KAL-2026-017',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-018',
                'name' => 'Megger MIT525 5kV',
                'merk_type' => 'Megger MIT525',
                'serial_number' => 'MGR-MIT525-10101010',
                'kode_inventaris' => 'INV-ALT-018',
                'description' => 'Tester resistansi isolasi 5kV.',
                'cabang_id' => $jambi->id,
                'lokasi' => 'Gudang Alat Jambi',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::Sewa->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Pending->value,
                'kalibrasis' => [],
            ],
            [
                'code' => 'ALT-019',
                'name' => 'Pychrometer Sling Whirling BS-CTH200',
                'merk_type' => 'BS-CTH200',
                'serial_number' => 'BS-CTH200-11111111',
                'kode_inventaris' => 'INV-ALT-019',
                'description' => 'Pengukur kelembaban relatif (sling psychrometer).',
                'cabang_id' => $pontianak->id,
                'lokasi' => 'Lab Meteorologi Pontianak',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(30),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2025-11-01',
                        'tanggal_kalibrasi_berikutnya' => now()->addDays(5)->format('Y-m-d'),
                        'vendor' => 'BS Calibration',
                        'sertifikat_no' => 'KAL-2025-019',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'Jatuh tempo 5 hari.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-020',
                'name' => 'Vibration Meter SKF VIB-21',
                'merk_type' => 'SKF VIB-21',
                'serial_number' => 'SKF-VIB21-12121212',
                'kode_inventaris' => 'INV-ALT-020',
                'description' => 'Pengukur getaran mesin rotasi.',
                'cabang_id' => $pekanbaru->id,
                'lokasi' => 'Workshop Pekanbaru',
                'kondisi' => AlatKondisi::RusakRingan->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(40),
                'approval_note' => 'Approved, perlu perbaikan minor.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2024-08-01',
                        'tanggal_kalibrasi_berikutnya' => '2025-08-01',
                        'vendor' => 'SKF Service',
                        'sertifikat_no' => 'KAL-2024-020',
                        'hasil' => KalibrasiHasil::PerluPerbaikan->value,
                        'catatan' => 'Perlu kalibrasi ulang setelah perbaikan.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-021',
                'name' => 'Densimeter Densitest DTM-100',
                'merk_type' => 'DTM-100',
                'serial_number' => 'DTM-100-13131313',
                'kode_inventaris' => 'INV-ALT-021',
                'description' => 'Pengukur densitas cairan.',
                'cabang_id' => $semarang->id,
                'lokasi' => 'Lab Uji Bahan Semarang',
                'kondisi' => AlatKondisi::Baik->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => true,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(22),
                'approval_note' => 'Approved.',
                'kalibrasis' => [
                    [
                        'tanggal_kalibrasi' => '2026-02-15',
                        'tanggal_kalibrasi_berikutnya' => '2027-02-15',
                        'vendor' => 'Densitest Calibration',
                        'sertifikat_no' => 'KAL-2026-021',
                        'hasil' => KalibrasiHasil::Lulus->value,
                        'catatan' => 'OK.',
                    ],
                ],
            ],
            [
                'code' => 'ALT-022',
                'name' => 'Weld Gauge Bridge Cam WG-BC300',
                'merk_type' => 'WG-BC300',
                'serial_number' => 'WG-BC300-14141414',
                'kode_inventaris' => 'INV-ALT-022',
                'description' => 'Pengukur dimensi las (fillet, undercut, dll).',
                'cabang_id' => $banten->id,
                'lokasi' => 'Workshop Welding Banten',
                'kondisi' => AlatKondisi::Hilang->value,
                'status_kepemilikan' => AlatStatusKepemilikan::MilikSendiri->value,
                'is_active' => false,
                'review_status' => AlatReviewStatus::Approved->value,
                'reviewed_by' => $admin?->id,
                'reviewed_at' => now()->subDays(50),
                'approval_note' => 'Approved sebelum hilang.',
                'kalibrasis' => [],
            ],
        ];

        foreach ($alats as $alatData) {
            $kalibrasisData = $alatData['kalibrasis'] ?? [];
            unset($alatData['kalibrasis']);

            $alat = Alat::firstOrCreate(
                ['code' => $alatData['code']],
                $alatData
            );

            foreach ($kalibrasisData as $kalData) {
                AlatKalibrasi::firstOrCreate(
                    [
                        'alat_id' => $alat->id,
                        'tanggal_kalibrasi' => $kalData['tanggal_kalibrasi'],
                    ],
                    array_merge(['alat_id' => $alat->id], $kalData)
                );
            }
        }
    }
}
